### ISSUE TITLE
A question about routes order...

### ISSUE THREAD

**Issue by 0xsimulacra** [angeris/cfmm-routing-code#3]
Hello,

Thank you for the great paper, the thoughtful explanation in it and the accompanied code. It really helps someone like me.

I have one or two question please :

1. If I understood very well your formulation about including transaction cost in the objective function and without thinking about the fact that the problem is solvable or not, the way you included the transaction cost  is by adding a constant transaction cost for each CFMM, meaning if we do one trade in that CFMM we'll have to pay that transaction cost, while in reality the transaction cost is dependent not on if we did a trade or not on a CFMM but on how many trades we did on that CFMM and your formula omit this detail. Am I right ?

Your response for these questions will be so much helpful.

**Comment by h4k333m** [comment]
For the first question:

1. I'm thinking about solving it as a  "salesman problem on a directed non cyclic graph", but I need to go trough my optimization course again to see how to do it and hoping solution for this exists (I'm familiar that the solution exists for non directed graphs). But thinking about the speed for getting the solution, Do you think that's a good approach ?

**Comment by angeris** [comment]
Thanks!

I think we will leave the question of how to add the gas cost of doing multiple trades on currently-implemented CFMMs as an exercise to the reader :)

(Maybe more specifically: there is no real reason why Balancer, e.g., can't allow multi-asset trades to happen in a single contract call, which is the case we were considering here.)
